HEMIS_MOCK_USERS = {
    "STU001": {
        "password": "student1",
        "student_id_number": "STU001",
        "full_name": "Akmalxon Yusupov",
        "email": "akmal.yusupov@student.ndki.uz",
        "phone": "+998901112233",
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Dasturiy injiniring",
        "group": "DI-22-01",
    },
    "STU002": {
        "password": "student2",
        "student_id_number": "STU002",
        "full_name": "Mohira Qodirova",
        "email": "mohira.qodirova@student.ndki.uz",
        "phone": "+998907654321",
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Kompyuter injiniringi",
        "group": "KI-22-02",
    },
    "STU003": {
        "password": "student3",
        "student_id_number": "STU003",
        "full_name": "Javohir Karimov",
        "email": "javohir.karimov@student.ndki.uz",
        "phone": "+998933334455",
        "faculty_name": "Iqtisodiyot",
        "department_name": "Bank ishi",
        "group": "BI-23-01",
    },
    "STU004": {
        "password": "student4",
        "student_id_number": "STU004",
        "full_name": "Diyora Sobirova",
        "email": "diyora.sobirova@student.ndki.uz",
        "phone": "+998935556677",
        "faculty_name": "Iqtisodiyot",
        "department_name": "Marketing",
        "group": "MK-23-02",
    },
    "STU005": {
        "password": "student5",
        "student_id_number": "STU005",
        "full_name": "Bekzod Toshmatov",
        "email": "bekzod.toshmatov@student.ndki.uz",
        "phone": "+998937778899",
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Dasturiy injiniring",
        "group": "DI-22-01",
    },
}
