HEMIS_MOCK_USERS: dict[str, dict] = {
    "STU001": {
        "password": "student1",
        "student_id_number": "STU001",
        "full_name": "Akmalxon Yusupov",
        "email": "akmal.yusupov@student.ndki.uz",
        "phone": "+998901112233",
        "birth_date": "2002-05-14",
        "gender": "male",
        "address": "Toshkent sh., Yunusobod t.",
        "image_path": None,
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Dasturiy injiniring",
        "specialty": "Dasturiy injiniring",
        "group": "DI-22-01",
        "level": 3,
        "semester": 5,
        "student_status": "O'qiydi",
        "education_form": "Kunduzgi",
        "education_type": "Bakalavr",
        "education_lang": "O'zbek",
        "payment_form": "Kontrakt",
    },
    "STU002": {
        "password": "student2",
        "student_id_number": "STU002",
        "full_name": "Mohira Qodirova",
        "email": "mohira.qodirova@student.ndki.uz",
        "phone": "+998907654321",
        "birth_date": "2003-08-22",
        "gender": "female",
        "address": "Toshkent v., Chirchiq sh.",
        "image_path": None,
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Kompyuter injiniringi",
        "specialty": "Kompyuter injiniringi",
        "group": "KI-22-02",
        "level": 3,
        "semester": 6,
        "student_status": "O'qiydi",
        "education_form": "Kunduzgi",
        "education_type": "Bakalavr",
        "education_lang": "O'zbek",
        "payment_form": "Grant",
    },
    "STU003": {
        "password": "student3",
        "student_id_number": "STU003",
        "full_name": "Javohir Karimov",
        "email": "javohir.karimov@student.ndki.uz",
        "phone": "+998933334455",
        "birth_date": "2004-01-10",
        "gender": "male",
        "address": "Samarqand v., Samarqand sh.",
        "image_path": None,
        "faculty_name": "Iqtisodiyot",
        "department_name": "Bank ishi",
        "specialty": "Bank ishi",
        "group": "BI-23-01",
        "level": 2,
        "semester": 3,
        "student_status": "O'qiydi",
        "education_form": "Kunduzgi",
        "education_type": "Bakalavr",
        "education_lang": "O'zbek",
        "payment_form": "Kontrakt",
    },
    "STU004": {
        "password": "student4",
        "student_id_number": "STU004",
        "full_name": "Diyora Sobirova",
        "email": "diyora.sobirova@student.ndki.uz",
        "phone": "+998935556677",
        "birth_date": "2003-11-30",
        "gender": "female",
        "address": "Farg'ona v., Farg'ona sh.",
        "image_path": None,
        "faculty_name": "Iqtisodiyot",
        "department_name": "Marketing",
        "specialty": "Marketing",
        "group": "MK-23-02",
        "level": 2,
        "semester": 4,
        "student_status": "O'qiydi",
        "education_form": "Kunduzgi",
        "education_type": "Bakalavr",
        "education_lang": "O'zbek",
        "payment_form": "Grant",
    },
    "STU005": {
        "password": "student5",
        "student_id_number": "STU005",
        "full_name": "Bekzod Toshmatov",
        "email": "bekzod.toshmatov@student.ndki.uz",
        "phone": "+998937778899",
        "birth_date": "2002-07-19",
        "gender": "male",
        "address": "Toshkent sh., Shayxontohur t.",
        "image_path": None,
        "faculty_name": "Axborot texnologiyalari",
        "department_name": "Dasturiy injiniring",
        "specialty": "Dasturiy injiniring",
        "group": "DI-22-01",
        "level": 3,
        "semester": 5,
        "student_status": "O'qiydi",
        "education_form": "Kunduzgi",
        "education_type": "Bakalavr",
        "education_lang": "O'zbek",
        "payment_form": "Grant",
    },
}
